// This file was generated by build.rs.
// Do not modify directly

mod day_1;
mod day_2;
mod day_4;
mod day_3;
mod day_5;
mod day_6;
mod day_7;
mod day_8;

pub fn get_solutions() -> Vec<Box<dyn crate::IsCorrect>> {
    vec![
        Box::new(crate::y2023::day_1::get_solution()),
        Box::new(crate::y2023::day_2::get_solution()),
        Box::new(crate::y2023::day_4::get_solution()),
        Box::new(crate::y2023::day_3::get_solution()),
        Box::new(crate::y2023::day_5::get_solution()),
        Box::new(crate::y2023::day_6::get_solution()),
        Box::new(crate::y2023::day_7::get_solution()),
        Box::new(crate::y2023::day_8::get_solution())
    ]
}
