// This file was generated by build.rs.
// Do not modify directly

mod day_2;
mod day_4;
mod day_6;
mod day_9;
mod day_5;
mod day_20;
mod day_3;
mod day_12;
mod day_8;
mod day_7;
mod day_11;
mod day_1;
mod day_13;
mod day_10;
mod day_14;
mod day_23;
mod day_25;
mod day_15;

pub fn get_solutions() -> Vec<Box<dyn crate::IsCorrect>> {
    vec![
        Box::new(crate::y2022::day_2::get_solution()),
        Box::new(crate::y2022::day_4::get_solution()),
        Box::new(crate::y2022::day_6::get_solution()),
        Box::new(crate::y2022::day_9::get_solution()),
        Box::new(crate::y2022::day_5::get_solution()),
        Box::new(crate::y2022::day_20::get_solution()),
        Box::new(crate::y2022::day_3::get_solution()),
        Box::new(crate::y2022::day_12::get_solution()),
        Box::new(crate::y2022::day_8::get_solution()),
        Box::new(crate::y2022::day_7::get_solution()),
        Box::new(crate::y2022::day_11::get_solution()),
        Box::new(crate::y2022::day_1::get_solution()),
        Box::new(crate::y2022::day_13::get_solution()),
        Box::new(crate::y2022::day_10::get_solution()),
        Box::new(crate::y2022::day_14::get_solution()),
        Box::new(crate::y2022::day_23::get_solution()),
        Box::new(crate::y2022::day_25::get_solution()),
        Box::new(crate::y2022::day_15::get_solution())
    ]
}
